# nympy 

In [1]:
import numpy as np

In [5]:
myarray = np.array([3,5,7,8])

In [6]:
myarray


array([3, 5, 7, 8])

In [7]:
myarray = np.array([3,5,7,8],np.int8)

In [8]:
myarray

array([3, 5, 7, 8], dtype=int8)

In [9]:
myarray = np.array([3,59867,7,8],np.int8)

In [10]:
myarray

array([  3, -37,   7,   8], dtype=int8)

In [11]:
myarray = np.array([3,5,7,8],np.int64)

In [12]:
myarray

array([3, 5, 7, 8], dtype=int64)

In [13]:
myarray[0]

3

In [14]:
myarray = np.array([[3,5,7,8]],np.int8)

In [15]:
myarray[0][0]

3

In [16]:
myarray[0][1]

5

In [17]:
myarray.shape

(1, 4)

In [18]:
myarray.dtype

dtype('int8')

In [19]:
myarray[0][1] =45


In [20]:
myarray

array([[ 3, 45,  7,  8]], dtype=int8)

# Array creation:Conversion from other Python structures (i.e. lists and tuples)

In [23]:
listarray=np.array([[2,4,6],[8,9,7],[8,3,4]])

In [24]:
listarray

array([[2, 4, 6],
       [8, 9, 7],
       [8, 3, 4]])

In [25]:
listarray.dtype


dtype('int32')

In [26]:
listarray.shape


(3, 3)

In [28]:
listarray.size

9

In [29]:
np.array({2,4})

array({2, 4}, dtype=object)

In [30]:
zeros = np.zeros((2,5))

In [31]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
zeros.shape


(2, 5)

In [33]:
zeros.dtype

dtype('float64')

In [34]:
zeros.size

10

In [35]:
rng = np.arange(15)

In [36]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
lspace = np.linspace(1,5,12)

In [38]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [39]:
lspace = np.linspace(1,4,2)

In [40]:
lspace

array([1., 4.])

In [41]:
emp = np.empty((4,6))

In [42]:
emp

array([[ 9.85940062e-312,  9.86107595e-312,  9.85940062e-312,
         9.86107595e-312,  9.85940062e-312,  9.86107595e-312],
       [ 9.86107595e-312, -1.13065821e-310,  9.86107595e-312,
         9.85940062e-312,  9.86107595e-312,  9.86107595e-312],
       [ 9.85940062e-312,  9.86107595e-312,  9.86107595e-312,
         9.85940062e-312,  9.86107595e-312,  9.86107595e-312],
       [ 9.85940062e-312,  9.86107595e-312,  9.86107595e-312,
         9.85940062e-312,  9.86107595e-312, -1.18498133e-310]])

In [43]:
emp_like = np.empty_like(lspace)

In [45]:
emp_like

array([1., 4.])

In [47]:
ide = np.identity(45)

In [48]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [49]:
ide.shape


(45, 45)

In [50]:
ide.size

2025

In [51]:
arr = np.arange(99)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
arr.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

In [55]:
arr = arr.reshape(3,33)

In [56]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [58]:
arr =arr.ravel()

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
arr.shape

(99,)

In [61]:
x = [[1,3,5],[5,8,9],[9,0,7]]

In [62]:
arr = np.array(x)

In [63]:
arr

array([[1, 3, 5],
       [5, 8, 9],
       [9, 0, 7]])

In [64]:
arr.sum(axis=0)

array([15, 11, 21])

In [65]:
arr.sum(axis=1)

array([ 9, 22, 16])

In [66]:
arr.T

array([[1, 5, 9],
       [3, 8, 0],
       [5, 9, 7]])

In [67]:
arr.flat


In [69]:
for item in arr.flat:
  print(item)

1
3
5
5
8
9
9
0
7


In [70]:
arr.ndim

2

In [71]:
arr.size

9

In [72]:
ar = np.array([3,5,6])

In [73]:
ar

array([3, 5, 6])

In [74]:
ar.ndim

1

In [75]:
ar.nbytes

12

In [76]:
arr.nbytes

36

In [77]:
one = np.array([8,0,6,5,55,88,99])

In [78]:
one.argmax()

6

In [79]:
one.argmin()

1

In [80]:
one.argsort()

array([1, 3, 2, 0, 4, 5, 6], dtype=int64)

In [81]:
arr

array([[1, 3, 5],
       [5, 8, 9],
       [9, 0, 7]])

In [82]:
arr.argmax()

5

In [83]:
arr.argmin()

7

In [84]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [85]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [86]:
arr.argsort(axis=0)

array([[0, 2, 0],
       [1, 0, 2],
       [2, 1, 1]], dtype=int64)

In [87]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [88]:
arr.ravel()

array([1, 3, 5, 5, 8, 9, 9, 0, 7])

In [89]:
arr.reshape((9,1))

array([[1],
       [3],
       [5],
       [5],
       [8],
       [9],
       [9],
       [0],
       [7]])

In [92]:
arr2=np.array([[4,8,9],[9,3,7],[8,9,0]])

In [93]:
arr+arr2

array([[ 5, 11, 14],
       [14, 11, 16],
       [17,  9,  7]])

In [94]:
arr


array([[1, 3, 5],
       [5, 8, 9],
       [9, 0, 7]])

In [95]:
arr2

array([[4, 8, 9],
       [9, 3, 7],
       [8, 9, 0]])

In [96]:
arr*arr2

array([[ 4, 24, 45],
       [45, 24, 63],
       [72,  0,  0]])

In [97]:
np.sqrt(arr)

array([[1.        , 1.73205081, 2.23606798],
       [2.23606798, 2.82842712, 3.        ],
       [3.        , 0.        , 2.64575131]])

In [98]:
arr.sum()

47

In [99]:
arr.min()

0

In [100]:
arr.max()

9

In [101]:
np.where(arr>7)

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [102]:
type(np.where(arr>7))

tuple

In [103]:
np.count_nonzero(arr)

8

In [104]:
import sys

In [105]:
py_ar = [4,7,99,8,7]

In [108]:
np_ar = np.array((py_ar))

In [109]:
sys.getsizeof(1)*len(py_ar)

140

In [111]:
np_ar.itemsize * np_ar.size

20

In [112]:
np_ar.tolist

<function ndarray.tolist>